import test from "node:test";
import assert from "node:assert/strict";
import { GameApplication } from "../index.ts";
import { createIsland } from "../../island/index.ts";

await test("terminal background clicks cannot resume physics or request capture in either control mode", () => {
  for (const keyboard of [true, false]) {
    const island = createIsland("starter-island");
    const app = new GameApplication(island);
    const entry = app.start(island, keyboard);
    if (!keyboard) {
      assert.equal(entry.kind, "capture");
      assert.equal(app.captureSucceeded(), true);
    }
    assert.equal(app.openTerminal(), true);
    const paused = app.state;
    assert.equal(app.resume("canvas").kind, "ignored");
    assert.equal(app.resume().kind, "ignored");
    assert.equal(app.press("Space"), false);
    app.tick(0.1);
    assert.equal(app.state, paused);
    assert.equal(app.terminalOpen, true);
    assert.equal(app.controlMode, "paused");
    assert.equal(app.captureSucceeded(), false);
    app.checkLink();
    assert.equal(app.state.linkChecked, true);
    const returned = app.resume("terminal");
    assert.equal(app.terminalOpen, false);
    assert.equal(returned.kind, keyboard ? "keyboard" : "capture");
    if (!keyboard) {
      assert.equal(app.state.paused, true);
      app.captureSucceeded();
    }
    app.press("Space");
    app.tick(0.1);
    assert.ok(app.state.y > paused.y);
  }
});

await test("welcome clicks do not start play; explicit pause return clears input", () => {
  const island = createIsland("starter-island");
  const app = new GameApplication(island);
  const initial = app.state;
  assert.equal(app.resume("canvas").kind, "ignored");
  assert.equal(app.resume("terminal").kind, "ignored");
  assert.equal(app.openTerminal(), false);
  app.checkLink();
  assert.equal(app.state, initial);
  assert.equal(app.started, false);
  app.start(island, true);
  app.press("KeyW");
  app.press("ArrowRight");
  app.press("Space");
  app.pause();
  const paused = app.state;
  app.tick(0.1);
  assert.equal(app.state, paused);
  assert.equal(app.captureLost(), true);
  assert.equal(app.resume().kind, "keyboard");
  app.tick(0.1);
  assert.equal(app.state.distance, 0);
  assert.equal(app.state.yaw, 0);
  assert.equal(app.state.grounded, true);
});
await test("capture cancellation and rejection cannot activate or cancel a newer lifecycle request", () => {
  const app = new GameApplication(createIsland());
  const first = app.start(app.island, false);
  assert.equal(first.kind, "capture");
  assert.equal(app.state.paused, true);
  assert.equal(app.resume().kind, "ignored");
  assert.equal(app.press("KeyW"), false);
  app.pause();
  assert.equal(app.captureSucceeded(), false);
  const second = app.resume();
  assert.equal(second.kind, "capture");
  assert.equal(app.captureFailed(first.generation), false);
  assert.equal(app.controlMode, "capturing");
  assert.equal(app.captureFailed(second.generation), true);
  assert.equal(app.state.paused, true);
  assert.equal(app.controlMode, "paused");
  assert.equal(app.captureFailed(), false);
  assert.equal(app.resume().kind, "capture");
  assert.equal(app.captureSucceeded(), true);
  assert.equal(app.state.paused, false);
  app.press("KeyW");
  assert.equal(app.captureLost(), true);
  assert.equal(app.state.paused, true);
  const beforeInputCheck = app.state;
  app.tick(0.05);
  assert.equal(app.state.distance, beforeInputCheck.distance);
});
await test("expected capture loss preserves a terminal; only explicit return requests capture", () => {
  const app = new GameApplication(createIsland());
  app.start(app.island, false);
  app.captureSucceeded();
  app.press("KeyW");
  app.openTerminal();
  const terminal = app.state;
  assert.equal(app.captureLost(), false);
  assert.equal(app.terminalOpen, true);
  const beforeInputCheck = app.state;
  app.tick(0.05);
  assert.equal(app.state.distance, beforeInputCheck.distance);
  assert.equal(app.captureFailed(), false);
  assert.equal(app.state, terminal);
  const returned = app.resume("terminal");
  assert.equal(returned.kind, "capture");
  assert.equal(app.state.paused, true);
  assert.equal(app.captureSucceeded(), true);
  assert.equal(app.terminalOpen, false);
});
await test("seed replacement clears the old terminal, progress and queued inputs and rejects old capture results", () => {
  const oldIsland = createIsland("starter-island");
  const nextIsland = createIsland("next-home");
  const app = new GameApplication(oldIsland);
  const oldCapture = app.start(oldIsland, false);
  assert.equal(oldCapture.kind, "capture");
  app.captureSucceeded();
  app.openTerminal();
  app.checkLink();
  assert.equal(app.state.linkChecked, true);
  app.resume("terminal");
  app.captureSucceeded();
  app.press("Space");
  app.press("KeyW");
  assert.equal(app.start(nextIsland, true).kind, "keyboard");
  assert.equal(app.island, nextIsland);
  assert.equal(app.state.x, nextIsland.spawn.x);
  assert.equal(app.state.z, nextIsland.spawn.z);
  assert.equal(app.state.linkChecked, false);
  assert.deepEqual(app.state.discovered, []);
  assert.equal(app.terminalOpen, false);
  assert.equal(app.captureSucceeded(), false);
  assert.equal(app.captureFailed(oldCapture.generation), false);
  app.tick(0.1);
  assert.equal(app.state.distance, 0);
  assert.equal(app.state.grounded, true);
});
await test("restart and seed chooser reset progress while retaining keyboard preference", () => {
  const app = new GameApplication(createIsland());
  app.start(app.island, true);
  app.openTerminal();
  app.checkLink();
  assert.equal(app.restart().kind, "keyboard");
  assert.equal(app.state.linkChecked, false);
  assert.equal(app.terminalOpen, false);
  assert.equal(app.started, true);
  app.press("Space");
  app.chooseSeed();
  assert.equal(app.started, false);
  assert.equal(app.state.paused, true);
  assert.equal(app.keyboardPreferred, true);
  const beforeInputCheck = app.state;
  app.tick(0.05);
  assert.equal(app.state.distance, beforeInputCheck.distance);
  assert.equal(app.resume("canvas").kind, "ignored");
});
await test("control switching and pause clear input and integrate real keyboard look and movement", () => {
  const app = new GameApplication(createIsland());
  app.start(app.island, true);
  app.press("KeyD");
  app.press("ArrowRight");
  app.tick(0.1);
  assert.ok(app.state.distance > 0);
  assert.ok(app.state.yaw < 0);
  app.pause();
  const paused = app.state;
  app.mouseMoved(100, 100, 1, false);
  app.tick(0.1);
  assert.equal(app.state, paused);
  assert.equal(app.resume("canvas").kind, "keyboard");
  assert.equal(app.captureLost(), false);
  assert.equal(app.switchControls().kind, "capture");
  assert.equal(app.keyboardPreferred, false);
  assert.equal(app.state.paused, true);
  app.captureSucceeded();
  app.pause();
  assert.equal(app.switchControls().kind, "keyboard");
  const beforeInputCheck = app.state;
  app.tick(0.05);
  assert.equal(app.state.distance, beforeInputCheck.distance);
});
await test("terminal cannot open out of range or while paused", () => {
  const app = new GameApplication(createIsland());
  app.start(app.island, true);
  app.press("KeyS");
  for (let i = 0; i < 20; i++) {
    app.tick(0.1);
  }
  assert.equal(app.openTerminal(), false);
  app.checkLink();
  assert.equal(app.state.linkChecked, false);
  app.restart();
  app.pause();
  assert.equal(app.openTerminal(), false);
});
