import test from "node:test";
import assert from "node:assert/strict";
import { GameApplication } from "../src/application.ts";
import { createIsland } from "../src/world.ts";
import { makeObstacles } from "../src/collision.ts";

await test("terminal background clicks cannot resume physics or request capture in either control mode", () => {
  for (const keyboard of [true, false]) {
    const island = createIsland("ember-home");
    const app = new GameApplication(island);
    const entry = app.start(island, keyboard);
    if (!keyboard) {
      assert.equal(entry.kind, "capture");
      assert.equal(app.captureSucceeded(), true);
    }
    assert.equal(app.openTerminal(), true);
    const paused = app.state;
    assert.equal(app.resume("canvas").kind, "ignored");
    assert.equal(app.resume().kind, "ignored");
    assert.equal(app.session.press("Space"), false);
    app.tick(0.1, makeObstacles(island));
    assert.equal(app.state, paused);
    assert.equal(app.terminalOpen, true);
    assert.equal(app.session.mode, "paused");
    assert.equal(app.captureSucceeded(), false);
    app.checkLink();
    assert.equal(app.state.linkChecked, true);
    const returned = app.resume("terminal");
    assert.equal(app.terminalOpen, false);
    assert.equal(returned.kind, keyboard ? "keyboard" : "capture");
    if (!keyboard) {
      assert.equal(app.state.paused, true);
      app.captureSucceeded();
    }
    app.session.press("Space");
    app.tick(0.1, makeObstacles(island));
    assert.ok(app.state.y > paused.y);
  }
});

await test("welcome and overview canvas clicks do not start play; explicit overview return does", () => {
  const island = createIsland("ember-home");
  const app = new GameApplication(island);
  const initial = app.state;
  assert.equal(app.resume("canvas").kind, "ignored");
  assert.equal(app.resume("terminal").kind, "ignored");
  assert.equal(app.openTerminal(), false);
  app.checkLink();
  assert.equal(app.state, initial);
  assert.equal(app.started, false);
  app.start(island, true);
  app.session.press("KeyW");
  app.session.press("ArrowRight");
  app.session.press("Space");
  app.pause(true);
  const overview = app.state;
  app.tick(0.1, makeObstacles(island));
  assert.equal(app.state, overview);
  assert.equal(app.resume("canvas").kind, "ignored");
  assert.equal(app.captureLost(), false);
  assert.equal(app.resume().kind, "keyboard");
  assert.equal(app.state.overview, false);
  app.tick(0.1, makeObstacles(island));
  assert.equal(app.state.distance, 0);
  assert.equal(app.state.yaw, 0);
  assert.equal(app.state.grounded, true);
});
await test("capture cancellation and rejection cannot activate or cancel a newer lifecycle request", () => {
  const app = new GameApplication(createIsland());
  const first = app.start(app.island, false);
  assert.equal(first.kind, "capture");
  assert.equal(app.state.paused, true);
  assert.equal(app.resume().kind, "ignored");
  assert.equal(app.session.press("KeyW"), false);
  app.pause();
  assert.equal(app.captureSucceeded(), false);
  const second = app.resume();
  assert.equal(second.kind, "capture");
  assert.equal(app.captureFailed(first.generation), false);
  assert.equal(app.session.mode, "capturing");
  assert.equal(app.captureFailed(second.generation), true);
  assert.equal(app.state.paused, true);
  assert.equal(app.session.mode, "paused");
  assert.equal(app.captureFailed(), false);
  assert.equal(app.resume().kind, "capture");
  assert.equal(app.captureSucceeded(), true);
  assert.equal(app.state.paused, false);
  app.session.press("KeyW");
  assert.equal(app.captureLost(), true);
  assert.equal(app.state.paused, true);
  assert.equal(app.session.readInput().forward, false);
});
await test("expected capture loss preserves a terminal; only explicit return requests capture", () => {
  const app = new GameApplication(createIsland());
  app.start(app.island, false);
  app.captureSucceeded();
  app.session.press("KeyW");
  app.openTerminal();
  const terminal = app.state;
  assert.equal(app.captureLost(), false);
  assert.equal(app.terminalOpen, true);
  assert.equal(app.session.readInput().forward, false);
  assert.equal(app.captureFailed(), false);
  assert.equal(app.state, terminal);
  const returned = app.resume("terminal");
  assert.equal(returned.kind, "capture");
  assert.equal(app.state.paused, true);
  assert.equal(app.captureSucceeded(), true);
  assert.equal(app.terminalOpen, false);
});
await test("seed replacement clears the old terminal, progress and queued inputs and rejects old capture results", () => {
  const oldIsland = createIsland("ember-home");
  const nextIsland = createIsland("next-home");
  const app = new GameApplication(oldIsland);
  const oldCapture = app.start(oldIsland, false);
  assert.equal(oldCapture.kind, "capture");
  app.captureSucceeded();
  app.openTerminal();
  app.checkLink();
  assert.equal(app.state.linkChecked, true);
  app.resume("terminal");
  app.captureSucceeded();
  app.session.press("Space");
  app.session.press("KeyW");
  assert.equal(app.start(nextIsland, true).kind, "keyboard");
  assert.equal(app.island, nextIsland);
  assert.equal(app.state.x, nextIsland.spawn.x);
  assert.equal(app.state.z, nextIsland.spawn.z);
  assert.equal(app.state.linkChecked, false);
  assert.deepEqual(app.state.discovered, []);
  assert.equal(app.terminalOpen, false);
  assert.equal(app.captureSucceeded(), false);
  assert.equal(app.captureFailed(oldCapture.generation), false);
  app.tick(0.1, makeObstacles(nextIsland));
  assert.equal(app.state.distance, 0);
  assert.equal(app.state.grounded, true);
});
await test("restart and seed chooser reset progress while retaining keyboard preference", () => {
  const app = new GameApplication(createIsland());
  app.start(app.island, true);
  app.openTerminal();
  app.checkLink();
  assert.equal(app.restart().kind, "keyboard");
  assert.equal(app.state.linkChecked, false);
  assert.equal(app.terminalOpen, false);
  assert.equal(app.started, true);
  app.session.press("Space");
  app.chooseSeed();
  assert.equal(app.started, false);
  assert.equal(app.state.paused, true);
  assert.equal(app.session.keyboardPreferred, true);
  assert.equal(app.session.readInput().jump, false);
  assert.equal(app.resume("canvas").kind, "ignored");
});
await test("control switching and pause clear input and integrate real keyboard look and movement", () => {
  const app = new GameApplication(createIsland());
  app.start(app.island, true);
  app.session.press("KeyD");
  app.session.press("ArrowRight");
  app.tick(0.1, makeObstacles(app.island));
  assert.ok(app.state.distance > 0);
  assert.ok(app.state.yaw < 0);
  app.pause();
  const paused = app.state;
  app.look(1, 1);
  app.tick(0.1, []);
  assert.equal(app.state, paused);
  assert.equal(app.resume("canvas").kind, "keyboard");
  assert.equal(app.captureLost(), false);
  assert.equal(app.switchControls().kind, "capture");
  assert.equal(app.session.keyboardPreferred, false);
  assert.equal(app.state.paused, true);
  app.captureSucceeded();
  app.pause();
  assert.equal(app.switchControls().kind, "keyboard");
  assert.equal(app.session.readInput().right, false);
});
await test("terminal cannot open out of range or while paused", () => {
  const app = new GameApplication(createIsland());
  app.start(app.island, true);
  app.session.press("KeyS");
  for (let i = 0; i < 20; i++) {
    app.tick(0.1, []);
  }
  assert.equal(app.openTerminal(), false);
  app.checkLink();
  assert.equal(app.state.linkChecked, false);
  app.restart();
  app.pause();
  assert.equal(app.openTerminal(), false);
});
