/** Offline table recipe. No platform trigonometry; fixed-decimal BigInt Taylor series. */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
const PI_DIGITS =
  "31415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679";
export function generateQuarterTable(precision = 90): number[] {
  if (!Number.isInteger(precision) || precision < 60 || precision > 90) {
    throw new RangeError("Precision must be 60..90 decimal places");
  }
  const scale = 10n ** BigInt(precision);
  const pi = BigInt(PI_DIGITS.slice(0, precision + 1));
  return Array.from({ length: 16_385 }, (_, index) => {
    if (index === 16_384) {
      return 16_777_216;
    }
    const x = (pi * BigInt(index)) / 32_768n;
    let term = x;
    let sum = x;
    for (let k = 1n; term !== 0n; k++) {
      term = (-term * x * x) / (scale * scale * (2n * k) * (2n * k + 1n));
      sum += term;
    }
    return Number((sum * 16_777_216n) / scale);
  });
}
export function tableChecksum(values: readonly number[]): string {
  const bytes = Buffer.alloc(values.length * 4);
  values.forEach((value, index) => bytes.writeInt32LE(value, index * 4));
  return createHash("sha256").update(bytes).digest("hex");
}
export function tableSource(): string {
  const values = generateQuarterTable();
  return `// Generated by npm run numeric:generate. Q24 table v1; do not edit.\nexport const TABLE_SHA256 =\n  "${tableChecksum(values)}";\n// prettier-ignore\nexport const QUARTER_SINE: readonly number[] = Object.freeze([${values.join(",")}]);\n`;
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const target = new URL("./lib/directions-table.ts", import.meta.url);
  const source = tableSource();
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== source) {
      throw new Error("Direction table differs from reproducible recipe");
    }
  } else {
    writeFileSync(target, source);
  }
}
